# Jekyll Defaults
title: Chloeyiyi
subtitle: Blog
description: Demo
baseurl: "https://ywz0210.github.io" # the subpath of your site, e.g. /blog

url: "https://ywz0210.github.io"
github: ywz0210
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Proj
  url: /proj/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
